name: Auto Branch for Issue

on:
  issues:
    types: [assigned]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT}}

      - name: Create and push branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE// /-}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | cut -c1-63)
          echo "Branch name: $BRANCH_NAME"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 🔥 THIS IS THE MOST IMPORTANT LINE 🔥
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

          git fetch origin
          git checkout origin/main
          git checkout -b "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
