name: Auto Branch for Issue

on:
  issues:
    types: [assigned]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}  # this ensures the initial checkout uses your token

      - name: Create and push branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Build branch name from issue
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE// /-}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | cut -c1-63)
          echo "Creating branch: $BRANCH_NAME"

          # Set Git bot user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Reset the remote URL with the token to authenticate fetch/push
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

          # Ensure we're on default branch (assumes it's 'main'; change if needed)
          git fetch origin
          git checkout origin/main
          git checkout -b "$BRANCH_NAME"

          # Push new branch
          git push -u origin "$BRANCH_NAME"
